DELETE FROM Attendance;
DELETE FROM Child;
DELETE FROM Parent;
DELETE FROM School;

ALTER TABLE Attendance ALTER COLUMN id RESTART WITH 1;
ALTER TABLE Child ALTER COLUMN id RESTART WITH 1;
ALTER TABLE Parent ALTER COLUMN id RESTART WITH 1;
ALTER TABLE School ALTER COLUMN id RESTART WITH 1;